---
- name: Paso 1 conexion
  hosts: localhost
  connection: local
  vars:
    cyberark_url: https://srvpampvwadr.bcch.local/PasswordVault
    CyberArk_User: "{{ CyberArk_User_var }}"
    CyberArk_Password: "{{ CyberArk_Password_var }}"
    cuentas_maquina: "{{ nombre_server_var }}" 
  tasks:
    - name: obtener token
      ansible.builtin.uri:
        method: POST
        validate_certs: no
        return_content: yes
        url: "{{ cyberark_url}}/API/auth/Cyberark/Logon"
        body_format: json
        body: 
          username: "{{ CyberArk_User }}"
          password: "{{ CyberArk_Password }}"
      register: _token
    - name: mostrar token
      debug:
        msg: "{{ _token.content | from_json }}"
    
    - name: Busco cuentas disponibles en el Cyberark
      ansible.builtin.uri:
        method: GET
        validate_certs: no
        return_content: yes
        url: "{{ cyberark_url }}/API/Accounts?search={{ cuentas_maquina }}&searchtype=contains&limit=5"
        body_format: json
        headers:
          Authorization: "{{ _token.content | from_json }}"
      register: cyberark_accounts

    - name: Resultado cyberark_accounts 
      debug:
        msg: "{{ cyberark_accounts | json_query 'userName[?userName = `root`].id')}}"

