---
- name: Paso 1 conexion
  hosts: localhost
  connection: local
  vars:
    PVWA: https://srvpampvwadr.bcch.local/PasswordVault
    CyberArk_User: "{{ CyberArk_User_var }}"
    CyberArk_Password: "{{ CyberArk_Password_var }}"
  
  tasks:
    - name: obtener token
      ansible.builtin.uri:
        method: POST
        validate_certs: no
        return_content: yes
        url: "{{ PVWA }}/API/auth/Cyberark/Logon"
        body_format: json
        body: 
          username: "{{ CyberArk_User }}"
          password: "{{ CyberArk_Password }}"
      register: _token
    - name: mostrar token
      debug:
        msg: "{{ _token.content | from_json }}"
    
    - name: Busco cuentas disponibles en el Cyberark
      ansible.builtin.uri:
        url: "{{ cyberark_url }}/PasswordVault/API/Accounts/"
        method: GET
        validate_certs: false
        return_content: true
        headers:
          Authorization: "{{ cyberark_login.content | from_json }}"
      register: cyberark_accounts

    - name: Resultado cyberark_accounts 
      debug:
        msg: "{{ cyberark_accounts }}"

