---
- name: Obtener contenido de un archivo
  hosts: localhost
  tasks:
    - name: obtener token
      ansible.builtin.uri:
        url: https://srvpampvwadr.bcch.local/PasswordVault/API/auth/CyberArk/logon
        method: POST
        body_format: form-urlencoded
        Content-Type: application/json
        return_content: true
        body:
          name: username
          password: password
      register: token
    - name: mostrar token
      debug:
        msg: token.stdout
