---
- name: Paso 1 conexion
  hosts: localhost
  connection: local
  vars:
    PVWA: https://srvpampvwadr.bcch.local/PasswordVault
    CyberArk_User: "{{ CyberArk_User_var }}"
    CyberArk_Password: "{{ CyberArk_Password_var }}"
  
  tasks:
    - name: obtener token
      ansible.builtin.uri:
        method: POST
        validate_certs: no
        return_content: yes
        url: "{{ PVWA }}/API/auth/Cyberark/Logon"
        body_format: json
        body: 
          username: "{{ CyberArk_User }}"
          password: "{{ CyberArk_Password }}"
      register: _token
    - name: mostrar token
      debug:
        msg: "{{ _token.content | from_json }}"


