---
- name: Connect to Hitachi Ops Center
  hosts: localhost 
  gather_facts: no  

  tasks:
    - name: Authenticate with Hitachi Ops Center
      uri:
        url: "{{hitachiurl_var}}/API/7.1/master/UIController/services/Users/actions/login/invoke"
        method: POST
        headers:
          Content-Type: "application/json"
          Cookie: "demosession"
        body_format: form-urlencoded
        body: "username={{hitachi_user_var}}&password={{hitachi_password_var}}&space=master"
        validate_certs: no  
      register: login_response

    - name: chequeo de conexion
      fail:
        msg: "Authentication failed"
      when: login_response.status != 200

    #- name: Perform Hitachi Ops Center actions
      # Add tasks here to interact with Hitachi Ops Center using appropriate Ansible modules or custom tasks
#curl --insecure --cookie-jar demosession --data "username=user&password=password&space=master" "https://demomaster/API/7.1/master/UIController/services/Users/actions/login/invoke" –silent
