---
- name: Connect to Hitachi Ops Center
  hosts: localhost 
  gather_facts: no  

  tasks:
    - name: Authenticate with Hitachi Ops Center
      uri:
        url: "{{hitachiurl_var}}/v1/security/tokens"
        method: POST
        validate_certs: no 
        return_content: yes 
        user: "{{hitachi_user_var}}"
        password: "{{hitachi_password_var}}"
        force_basic_auth: yes
        validate_certs: no  
      register: hitachi_token

    - name: chequeo login
      debug: 
        msg: "{{hitachi_token.content}}"
