---
- name: Connect to Hitachi Ops Center
  hosts: localhost 
  gather_facts: no  

  tasks:
    - name: Authenticate with Hitachi Ops Center
      uri:
        url: "{{hitachiurl_var}}/HDID/master/UIController/services/Users/actions/login/invoke"
#        url: "{{hitachiurl_var}}/ConfigurationManager/v1/objects/storages/####/sessions
        method: get
        validate_certs: no 
        return_content: yes 
#        headers:
#          Content-Type: "application/json"
#          Cookie: "demosession"
#        body_format: form-urlencoded
        user: "{{hitachi_user_var}}"
        password: "{{hitachi_password_var}}"
        space: Master
        force_bsic_auth: yes
        validate_certs: no  
      register: _login

    - name: chequeo login
      debug: 
        msg: "{{_login}}"
